// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAafWsG7KzUME3ojwFGP1uoOwKQRPzCDC0',
    appId: '1:820070470572:web:ac0f77c24c6b98c7476009',
    messagingSenderId: '820070470572',
    projectId: 'in-lab-activity-ae9cd',
    authDomain: 'in-lab-activity-ae9cd.firebaseapp.com',
    storageBucket: 'in-lab-activity-ae9cd.appspot.com',
    measurementId: 'G-1CH6D421YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnfhNU_Q8VXqo4LTIYmbusFvWUUSJu6A',
    appId: '1:820070470572:android:c5e6f82af7183886476009',
    messagingSenderId: '820070470572',
    projectId: 'in-lab-activity-ae9cd',
    storageBucket: 'in-lab-activity-ae9cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJcfy_GLIoFauI3dMrmehv-qJAoGeguHw',
    appId: '1:820070470572:ios:46e0809a2b857e88476009',
    messagingSenderId: '820070470572',
    projectId: 'in-lab-activity-ae9cd',
    storageBucket: 'in-lab-activity-ae9cd.appspot.com',
    iosClientId: '820070470572-791bagnc6kpqi2ni5l6fakd31n0uridg.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJcfy_GLIoFauI3dMrmehv-qJAoGeguHw',
    appId: '1:820070470572:ios:46e0809a2b857e88476009',
    messagingSenderId: '820070470572',
    projectId: 'in-lab-activity-ae9cd',
    storageBucket: 'in-lab-activity-ae9cd.appspot.com',
    iosClientId: '820070470572-791bagnc6kpqi2ni5l6fakd31n0uridg.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipies',
  );
}
